### ISSUE TITLE
[Feature] Allow specifying manifest files

### ISSUE THREAD

**Issue by ipsi** [bluemixgaragelondon/cf-blue-green-deploy#10]
Currently, there is no possibility to explicitly specify a manifest when doing a blue-green deploy. I would like to be able to do something like the following:

```
cf bgd manifest-uat.yml app-name --smok-tests ./smoke_tests.sh
```

This can be worked around by putting the manifest files in separate directories, but that doesn't feel like a great solution, and makes working with them more awkward than it needs to be.

**Comment by yhjhoo** [comment]
it's better if it is accepting the other cf parameters
