### ISSUE TITLE
Need better error when fail to get default shared domain

### ISSUE THREAD

**Issue by bjulbricht** [bluemixgaragelondon/cf-blue-green-deploy#11]
I'm trying to use the blue-green-deploy plugin, but keep getting the error "Failed to get default shared domain".  I enabled CF_TRACE=true to see the request/response, and the response looks OK to my untrained eye.

REQUEST: [2016-07-10T02:55:48Z]
GET /v2/shared_domains HTTP/1.1
Host: api.stage1.ng.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.20.0+25b1961 / linux

RESPONSE: [2016-07-10T02:55:49Z]
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/json;charset=utf-8
Date: Sun, 10 Jul 2016 02:55:49 GMT
Server: nginx
X-Backside-Transport: OK OK
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 417843439

1e5
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "80f7b34d-0c35-47d5-b14a-c0974a9d9b8c",
        "url": "/v2/shared_domains/80f7b34d-0c35-47d5-b14a-c0974a9d9b8c",
        "created_at": "2014-05-21T14:53:48Z",
        "updated_at": null
      },
      "entity": {
        "name": "stage1.mybluemix.net",
        "router_group_guid": null,
        "router_group_type": null
      }
    }
  ]
}
0

Failed to get default shared domain

//=======================================================

I see the implementation of 'DefaultCfDomain' in main.go, and it seems to me that it should be able to find 'stage1.mybluemix.net' when using statement 'response.Resources[0].Entity.Name'. Can anyone help? I definitely think propagating more of the error back to the user than just saying the DefaultCfDomain can't be found would be helpful.

```
func (p *CfPlugin) DefaultCfDomain() (domain string, err error) {
    var res []string
    if res, err = p.Connection.CliCommandWithoutTerminalOutput("curl", "/v2/shared_domains"); err != nil {
        return
    }

    response := struct {
        Resources []struct {
            Entity struct {
                Name string
            }
        }
    }{}

    if err = json.Unmarshal([]byte(res[0]), &response); err != nil {
        return
    }

    domain = response.Resources[0].Entity.Name
    return
}
```

**Comment by bjulbricht** [comment]
Based off the referenced issue ( #866 ), I downgraded my CF CLI to 6.16.1 and it works successfully.

**Comment by timjacobi** [comment]
Which CLI and plugin version are you seeing this error on. I will try to reproduce.

**Comment by bluemixgaragelondon** [comment]
The issue which caused this error on cf cli v 6.22.1 should now be fixed, but I don't think we've yet done the piece to propagate a better error back to the user, so leaving this open.

**Comment by balteo** [comment]
I use the following version of the CF CLI:

`cf version 6.26.0+9c9a261fd.2017-04-06, Cloud Foundry command line tool`

I run the following command:

`cf blue-green-deploy bignibou-server -f ./cf-bignibou-server-manifest.yml `

and I get the following error:

```
cf blue-green-deploy bignibou-server -f ./cf-bignibou-server-manifest.yml 

REQUEST: [2017-05-22T20:04:37+02:00]
GET /v2/shared_domains HTTP/1.1
Host: api.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261fd.2017-04-06 / darwin



RESPONSE: [2017-05-22T20:04:37+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 900
Content-Type: application/json;charset=utf-8
Date: Mon, 22 May 2017 18:04:34 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 20000
X-Ratelimit-Remaining: 19470
X-Ratelimit-Reset: 1495478889
X-Vcap-Request-Id: 7340a57c-61a7-4399-4133-4a5934f8d271
X-Vcap-Request-Id: cda6b558-2f32-4def-7790-e8676cf77b57::506d9a60-2c95-4fc6-8a4e-3c3975d7b6ed

{
  "total_results": 2,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "fb6bd89f-2ed9-49d4-9ad1-97951a573135",
        "url": "/v2/shared_domains/fb6bd89f-2ed9-49d4-9ad1-97951a573135",
        "created_at": "2013-05-04T00:29:46Z",
        "updated_at": "2017-05-19T00:45:19Z"
      },
      "entity": {
        "name": "cfapps.io",
        "router_group_guid": null,
        "router_group_type": null
      }
    },
    {
      "metadata": {
        "guid": "d42961c0-8361-4d60-bf58-9a3c1f09600a",
        "url": "/v2/shared_domains/d42961c0-8361-4d60-bf58-9a3c1f09600a",
        "created_at": "2016-09-08T21:22:28Z",
        "updated_at": null
      },
      "entity": {
        "name": "cf-tcpapps.io",
        "router_group_guid": "ac86636b-fc8b-46d7-49c4-edce5118daf2",
        "router_group_type": "tcp"
      }
    }
  ]
}
Failed to get default shared domain: unexpected end of JSON input
```
Is it a regression on the CLI or am I missing something?
