### ISSUE TITLE
Basic auth prevents health check

### ISSUE THREAD

**Issue by petschni** [bluemixgaragelondon/cf-blue-green-deploy#14]
We have a basic auth protection for our app. Unfortunately that leads to a 401 http code which is treated as an error. Could you change the check so that it does not fail the code?

```
 state     since                    cpu    memory          disk           details   
#0   running   2016-07-26 07:09:10 PM   0.0%   79.5M of 256M   110.7M of 1G      
+ curl --fail -I https://xyz-B.eu-gb.mybluemix.net
curl: (22) The requested URL returned error: 401 Unauthorised
++ on_fail
++ finally
++ rm /var/folders/gb/xyz_manifest.XXXXXXXXXX.eZF3dqmA
++ echo 'DEPLOY FAILED - you may need to check '\''cf apps'\'' and '\''cf routes'\'' and do manual cleanup'
DEPLOY FAILED - you may need to check 'cf apps' and 'cf routes' and do manual cleanup
```

**Comment by Samze** [comment]
It looks like you are having problems with this script, not our plugin. https://github.com/18F/cf-blue-green/blob/93f8d628d950272b7428d3156c36ae7abe613b3c/bin/cf-blue-green

However, our plugin allows you to define a custom smoke-test script instead. So you can decide what http codes are valid or not.
