### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by azizabah** [bluemixgaragelondon/cf-blue-green-deploy#2]
Whenever I try to install this plugin, I get the following error:
Looking up 'blue-green-deploy' from repository 'CF-Community'
10093904 bytes downloaded...
Installing plugin /tmp/ filename=blue-green-deploy.osx...
FAILED
exit status 2

I can successfully install other plugins from the CF-Community repo. I checked since my normal culprit is our corporate proxy but that doesn't seem to be the case this time. 

I am running Mac OSX 10.10.5.

**Comment by Samze** [comment]
Hey @azizabah, can you successfully pull it from our private repo?

```
cf add-plugin-repo garage https://garage-cf-plugins.eu-gb.mybluemix.net/
cf install-plugin blue-green-deploy -r garage
```

**Comment by azizabah** [comment]
No. I can't actually add your repo as https. If I attempt that I get this: 
FAILED
There is an error performing request on 'https://garage-cf-plugins.eu-gb.mybluemix.net/list': %!(EXTRA string=Get https://garage-cf-plugins.eu-gb.mybluemix.net/list: Found)
FAILED
There is an error performing request on 'https://garage-cf-plugins.eu-gb.mybluemix.net/list': %!(EXTRA string=Get https://garage-cf-plugins.eu-gb.mybluemix.net/list: Found)

I can add it as http though. If I do that, it fails with the same exit status as the CF-Community repo attempt.

**Comment by Samze** [comment]
What version of the CF cli are you using?

Could you also try backing up and then deleting your cf plugin directory, which should be located `~/.cf/plugins` and trying again?

You could also try downloading the binary directly and install it manually
```
$ wget https://github.com/bluemixgaragelondon/cf-blue-green-deploy/releases/download/v1.0.4/blue-green-deploy.osx
$ chmod +x blue-green-deploy.osx
$ cf install-plugin blue-green-deploy.osx
```

**Comment by azizabah** [comment]
I was using 6.11.3. I just updated to 6.14.1 to see if that would resolve the issue. It did not. 

I deleted the plugins folder and attempted to install from CF-Community repo, garage repo, and locally following your directions above. All three failed with exit status 2.

**Comment by Samze** [comment]
Very mysterious!

Could you try the following test?

1. Check if you have netcat installed by running the terminal command "nc".
2. In one terminal window, listen on port 12345 using this command (may have to run it as sudo)
```nc -vlk 12345```

3. While leaving that running, in a second terminal window invoke the plugin directly using this command.
```./blue-green-deploy.osx 12345 SendMetadata```

What does your netcat server window output? 

Additionally, what shell are you using? And do you have an example plugin from https://plugins.cloudfoundry.org/ui/ that you can install successfully?

**Comment by azizabah** [comment]
That found it. It's dying when it's trying to execute this: 
runtime stack:
runtime.throw(0x6a5155)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.4.2-cross/src/runtime/panic.go:491 +0xad fp=0x7fff5fbffb00 sp=0x7fff5fbffad0
runtime.goenvs()
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.4.2-cross/src/runtime/os_darwin.c:104 +0x70 fp=0x7fff5fbffb18 sp=0x7fff5fbffb00
runtime.schedinit()
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.4.2-cross/src/runtime/proc.c:141 +0x5f fp=0x7fff5fbffb40 sp=0x7fff5fbffb18
runtime.rt0_go(0x7fff5fbffb78, 0x3, 0x7fff5fbffb78, 0x0, 0x0, 0x3, 0x7fff5fbffc88, 0x7fff5fbffca0, 0x7fff5fbffca6, 0x0, ...)
	/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.4.2-cross/src/runtime/asm_amd64.s:95 +0x116 fp=0x7fff5fbffb48 sp=0x7fff5fbffb40

Apparently we have Go-related issues with an internal security application running on our machines. I'll go pester them about it.

Thanks for the assistance!

**Comment by Samze** [comment]
No problem! Let us know what you think of the plugin!
