### ISSUE TITLE
Routes in manifest (specified with 'routes' instead of 'host' or 'domain') are not honoured

### ISSUE THREAD

**Issue by holly-cummins** [bluemixgaragelondon/cf-blue-green-deploy#20]
See commit https://github.com/bluemixgaragelondon/cf-blue-green-deploy/commit/ae01d5acc50707560ba0659774394fc78bf150a0 (disabled test) to reproduce.

**Comment by jimmycarr** [comment]
Fixed to check for specific route rather than constructed route from host/domain.
