### ISSUE TITLE
Parameter -f manifest file not used

### ISSUE THREAD

**Issue by ejust** [bluemixgaragelondon/cf-blue-green-deploy#21]
Hello,

When I try to specify a custom manifest file, the plugin don't used it, but the default manifest.yml.

` cf blue-green-deploy batch -f manifest-batch.yml`

Result:

`Using manifest file /var/jenkins_home/workspace/project_develop/manifest.yml`

**Comment by holly-cummins** [comment]
The pull request which added this behaviour is in the codebase, but we haven't done an official release with it yet. 

You can use the version from our staging repo if you'd like to confirm (or get going with a different manifest before the release happens):

    cf add-plugin-repo CF-Garage https://garage-cf-plugins.eu-gb.mybluemix.net
    cf install-plugin -f blue-green-deploy -r CF-Garage
    cf bgd ${CF_APP}

**Comment by bluemixgaragelondon** [comment]
Fixed in #18
