### ISSUE TITLE
Panic when binary is run without arguments

### ISSUE THREAD

**Issue by rrufus** [bluemixgaragelondon/cf-blue-green-deploy#24]
It would be nicer if the binary would supply a list of expected arguments when the program is run without arguments e.g. `./cf-blue-green-deploy`.

**Comment by dcarley** [comment]
I've raised an upstream PR cloudfoundry/cli#1076 which should address this (when merged and rebuilt against).

**Comment by rrufus** [comment]
@dcarley thank you! When the PR is merged I will close the issue.

**Comment by rrufus** [comment]
The PR is now merged.
