### ISSUE TITLE
Feature proposal: delete -old app on success

### ISSUE THREAD

**Issue by dcarley** [bluemixgaragelondon/cf-blue-green-deploy#29]
Is there a reason that the `-old` suffixed app is left running after a successful deployment?

Would you accept a PR to automatically remove it when the deploy was successful?

Would you need the behaviour to be feature flagged with a new CLI argument?

**Comment by holly-cummins** [comment]
As it happens, this has been on our todo list, so we'd be really happy to take a pull request. (Thanks!) When we'd thought of it we'd concluded a feature flag would be best, and suggested --delete-old. I have to say I'm not sure there are enough cases where keeping the old app is desirable that the default shouldn't be delete, with the flag being --keep-old, but let's see what others think.

**Comment by timjacobi** [comment]
Interesting situation. To sum it up:
* `--keep-old` is preferable since deleting old apps makes more sense in most cases
* Deleting old apps by default might break existing usages since the default currently is to keep old apps

To address this I suggest the following (given current release is n)
* Deprecate keeping old apps in release n+1
* Add deprecation note to release notes of release n+1
* Introduce `--keep-old` flag in release n+1
* * If flag is not set display deprecation warning informing the user that old apps will be deleted in version n+2 if flag is not set
* Replace the warning by the code that actually deletes old apps in release n+2

**Comment by dcarley** [comment]
Sorry for the slow response, I was on leave for a week.

That sounds like a good plan. I'm happy to submit 2 PRs which implement that, the 2nd of which would need to be rebased nearer the time.

I've got two questions (for now) about the implementation:

1. Is `fmt.Println()` sufficient for printing the deprecation notice in n+1? Does it need tests, or is sufficient to test that the additional call to delete the app does/doesn't happen in n+2?
2. I presume you'll handle the release management? How much would you like me to do; update changelog?

**Comment by dcarley** [comment]
@holly-cummins @timjacobi I'm happy to do more work on this. Any thoughts about my questions?

**Comment by xenogew** [comment]
It's the idea I agree with.
And I think should we keep '-old' in some case like manual test is not pass or it has fatal bug on the '-new' app.
So I would like to raise the idea if we keep-old, we should have an option to bring-old-back immediately, when we found the fatal situation after deployment.

**Comment by dharries** [comment]
I think this is a  useful feature but I think we should default the flag the other way (i.e. `--delete-old`) for the following reasons:

1. Backward compatibility: I don’t think we should break this unless we really need to.  If people have bgd in scripts this change could break them.  If we do break compatibility it needs to be a new major semver release

1. It means that users can’t manually roll back if they find a problem with a new deployment.  See also https://github.com/bluemixgaragelondon/cf-blue-green-deploy/issues/7

1. It makes it unpredictable how many instances will be running after the deploy.  If a deploy fails then the old version AND the failed version will be left running, i.e. 2x the number for the successful case.  If we decided that we should also delete the failed app, that might make it difficult to debug a transient problem with the app deploy.

**Comment by SirWayne** [comment]
Deleting the old app would be 1 option, for us it's enough if we could disable the old app, because we do not want to lose service bindings

**Comment by metacubed** [comment]
Just stopping the `-old` app or scaling its instances to 0 would also work. The goal is to release used resources (like memory and disk) while keeping the old env and bindings for reference.

**Comment by Agisbert** [comment]
Seems this would be solved whenever the following merge request is done: 

https://github.com/bluemixgaragelondon/cf-blue-green-deploy/pull/56

**Comment by holly-cummins** [comment]
See also discussion (and a quasi-poll) on https://github.com/bluemixgaragelondon/cf-blue-green-deploy/pull/56.

**Comment by holly-cummins** [comment]
#56 is now merged, but is possibly too strong a change; I've added an additional pull request, #72, which flips the options (following @skyfalke's suggestion), and also updates the app deletion to not delete apps which failed to deploy or failed the smoke test. Having the smoking shell available for inspection will be important for diagnostics.
