### ISSUE TITLE
-f argument not used

### ISSUE THREAD

**Issue by dhrapson** [bluemixgaragelondon/cf-blue-green-deploy#33]
We are seeing behaviour that looks like the argument to `-f` is not being used.
When we create a manifest.yml file, place it in the current directory, and run `cf blue-green-deploy myapp`, the output clearly states:
`Using manifest file /path/to/manifest.yml`

However, running the command from some other directory with `-f /path/to/manifest.yml` added to the command arguments causes that same statement *not* to be output & our deployment fails.

We were not sure whether the `-f` argument is still supported because it does not appear in the `help` statement for blue-green-deploy, although it is present in the plugin README.md.

**Comment by holly-cummins** [comment]
See also https://github.com/bluemixgaragelondon/cf-blue-green-deploy/issues/21. The README.md is a bit ahead of the binary release.

You can use the version from our staging repo if you'd like to confirm (or get going with a different manifest before the release happens):

    cf add-plugin-repo CF-Garage https://garage-cf-plugins.eu-gb.mybluemix.net
    cf install-plugin -f blue-green-deploy -r CF-Garage
    cf bgd ${CF_APP}

**Comment by dhrapson** [comment]
OK. Thanks.
