### ISSUE TITLE
OSX version 1.2.0 reports version 1.1.0

### ISSUE THREAD

**Issue by henrytk** [bluemixgaragelondon/cf-blue-green-deploy#42]
When downloading [version 1.2.0](https://github.com/bluemixgaragelondon/cf-blue-green-deploy/releases/tag/v1.2.0) [for OSX](https://github.com/bluemixgaragelondon/cf-blue-green-deploy/releases/download/v1.2.0/blue-green-deploy.osx) and installing it says:

```
Installing plugin blue-green-deploy.osx...
OK
Plugin blue-green-deploy v1.1.0 successfully installed.
```

This presumably is a publishing error looking at your scripting.

**Comment by holly-cummins** [comment]
This is now fixed in the version of the plugin in the community repo. We've advanced the version number to 1.3 to reflect the inclusion of some new function, and avoid any confusion with the earlier version 1.2/1.1.
