### ISSUE TITLE
Route is not removed after DeleteAppVersions cleans up the app

### ISSUE THREAD

**Issue by grzegorzjudas** [bluemixgaragelondon/cf-blue-green-deploy#44]
Hello,

A while ago, I noticed that PCF does not remove the route itself, when app is removed. I discovered it, when I ran `cf delete-orphaned-routes -f` in a space, that was used by Jenkins for some time - there were a lot of old, unused routes, all with "-new" suffix.

Maybe it's a good idea to implement that into the code, to completely clean up after itself? The command is simply `cf delete-route [routeName]-new -f`.

**Comment by holgero** [comment]
This is also fixed in our PR #50

**Comment by holly-cummins** [comment]
Marking this closed, since it's fixed in the PR for #50 , which has been merged (although it's not yet in a release, only in the nightly builds).
