### ISSUE TITLE
Please release new version on CF-Community

### ISSUE THREAD

**Issue by bcanseco** [bluemixgaragelondon/cf-blue-green-deploy#74]
The README:
* provides instructions for installing from CF-Community
* mentions the new `--delete-old-apps` flag

However, the published version does not include support for that flag:
```shell
$ cf blue-green-deploy <app_name> --delete-old-apps
flag provided but not defined: -delete-old-apps
Usage of blue-green-deploy:
  -f string

  -smoke-test string
```

**Comment by holly-cummins** [comment]
You're quite right, to get that function the bleeding-edge nightly build would have to be used. A release got stalled with holidays and other commitments, so we'll pick it up again.

**Comment by bluemixgaragelondon** [comment]
Pull request for the release here: https://github.com/cloudfoundry/cli-plugin-repo/pull/249

**Comment by holly-cummins** [comment]
Release now on https://plugins.cloudfoundry.org.
