### ISSUE TITLE
No 64-bit Windows version available

### ISSUE THREAD

**Issue by ipsi** [bluemixgaragelondon/cf-blue-green-deploy#8]
I just attempted to install this plugin on Windows, and I received a message saying "Plugin requested has no binary available for your OS: windows, amd64".

Given that this plugin is written in Go, that's rather surprising to me. Is there a reason for the lack of a Windows version?

**Comment by holly-cummins** [comment]
A note on this: the issue is closed because the code is in the codebase, but it hasn't made it through a build into the plugin repository for various boring reasons. I'll comment again once the windows plugin is actually available for installation from a repo.

**Comment by bluemixgaragelondon** [comment]
The windows binaries are now available in the staging plugin repository. To try them out:

   cf add-plugin-repo CF-Garage https://garage-cf-plugins.eu-gb.mybluemix.net
   cf install-plugin -f blue-green-deploy -r CF-Garage
   cf bgd ${CF_APP}

Let me know if they do the trick, and if they're good I can work them through into a release on the CF community repository.

**Comment by mgoovaer** [comment]
@bluemixgaragelondon is this still active? I'm not able to install the plugin this way on a windows machine, am getting the following error: "Plugin requested has no binary available for your OS: windows, amd64"

**Comment by holly-cummins** [comment]
Hi, we're waiting for confirmation that the windows binaries work and then we'll do a release to get them into the CF Community Repo.  Looking at https://garage-cf-plugins.eu-gb.mybluemix.net/list, it looks like it's listed as windows64, not amd64. Will investigate - thanks.

**Comment by holly-cummins** [comment]
@mgoovaer, I've made an update to the repo. Would you mind trying the staging version of the plugin again?

    cf add-plugin-repo CF-Garage https://garage-cf-plugins.eu-gb.mybluemix.net
    cf install-plugin -f blue-green-deploy -r CF-Garage
    cf bgd ${CF_APP}

**Comment by mgoovaer** [comment]
@holly-cummins 
Hmm I'm getting this error when I try to install the plugin.

![screen shot 2017-01-13 at 2 28 56 pm](https://cloud.githubusercontent.com/assets/3597484/21942857/b224929c-d99c-11e6-8545-d36aefcb1811.png)

**Comment by holly-cummins** [comment]
Well, the good news is that it's got further. :) That may have been a build glitch caused by me only running half the process - I'll check. Thanks for testing it.

**Comment by mgoovaer** [comment]
@holly-cummins hmm now I'm getting a "file does not exist" error 
![screen_shot_2017-01-16_at_3 03 24_pm](https://cloud.githubusercontent.com/assets/3597484/21997409/24e20b5e-dbfd-11e6-8354-57f56cc4cbdb.png)

**Comment by bluemixgaragelondon** [comment]
It looks like that problem was caused by not having a file extension in the binary name. We've reproduced (for windows 32) and fixed, so now it should really *really* work. We think. :)

**Comment by mgoovaer** [comment]
@bluemixgaragelondon i was able to successfully install it, thanks!
